from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def replace_once(relative_path: str, old: str, new: str) -> None:
    path = ROOT / relative_path
    text = path.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise SystemExit(
            f"Expected one match in {relative_path}, found {count}: {old[:120]!r}"
        )
    path.write_text(text.replace(old, new, 1), encoding="utf-8")


def write(relative_path: str, content: str) -> None:
    path = ROOT / relative_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


# ---------------------------------------------------------------------------
# Version and Android permissions / services.

replace_once(
    "plugins/assistant/build.gradle.kts",
    '        versionCode = 9\n        versionName = "1.4.2"\n',
    '        versionCode = 10\n        versionName = "1.5.0"\n',
)

replace_once(
    "plugins/assistant/src/main/AndroidManifest.xml",
    '    <uses-permission android:name="android.permission.CALL_PHONE" />\n',
    '    <uses-permission android:name="android.permission.CALL_PHONE" />\n'
    '    <uses-permission android:name="android.permission.SEND_SMS" />\n'
    '    <uses-permission android:name="android.permission.READ_CALL_LOG" />\n',
)

replace_once(
    "plugins/assistant/src/main/AndroidManifest.xml",
    '        <service\n            android:name=".AssistantPluginService"\n',
    '        <service\n'
    '            android:name=".AssistantNotificationListenerService"\n'
    '            android:exported="true"\n'
    '            android:label="Assistant notification access"\n'
    '            android:permission="android.permission.BIND_NOTIFICATION_LISTENER_SERVICE">\n'
    '            <intent-filter>\n'
    '                <action android:name="android.service.notification.NotificationListenerService" />\n'
    '            </intent-filter>\n'
    '        </service>\n\n'
    '        <service\n            android:name=".AssistantPluginService"\n',
)

# ---------------------------------------------------------------------------
# Phone permission UI already generated by apply-assistant-phone-calls.py.

settings = "plugins/assistant/src/main/java/com/anezium/rokidbus/plugin/assistant/AssistantSettingsActivity.kt"
replace_once(
    settings,
    '                                            "Say ‘call…’ or ‘позвони…’ to place calls from your phone"\n',
    '                                            "Calls, redial and SMS are available by voice"\n',
)
replace_once(
    settings,
    '                                            "Allow the assistant to find contacts and place phone calls"\n',
    '                                            "Allow contacts, calls, call history and SMS"\n',
)
replace_once(
    settings,
    '            Manifest.permission.READ_CONTACTS,\n'
    '            Manifest.permission.CALL_PHONE,\n'
    '        )\n',
    '            Manifest.permission.READ_CONTACTS,\n'
    '            Manifest.permission.CALL_PHONE,\n'
    '            Manifest.permission.READ_CALL_LOG,\n'
    '            Manifest.permission.SEND_SMS,\n'
    '        )\n',
)

# ---------------------------------------------------------------------------
# Tool registry integration.

service = "plugins/assistant/src/main/java/com/anezium/rokidbus/plugin/assistant/AssistantPluginService.kt"
replace_once(
    service,
    '    private val phoneGateway by lazy { AndroidPhoneGateway(applicationContext) }\n',
    '    private val phoneGateway by lazy { AndroidPhoneGateway(applicationContext) }\n'
    '    private val smsGateway by lazy { AndroidSmsGateway(applicationContext) }\n'
    '    private val callHistoryGateway by lazy { AndroidCallHistoryGateway(applicationContext) }\n'
    '    private val meetingStore by lazy { AssistantMeetingStore() }\n'
    '    private val buildGroundBridge by lazy { BuildGroundDataBridge.disabled() }\n',
)
replace_once(
    service,
    '                assistantPhoneTools(phoneGateway),\n',
    '                assistantPhoneTools(phoneGateway) +\n'
    '                assistantMvpTools(\n'
    '                    calendarGateway = calendarGateway,\n'
    '                    reminderStore = reminderStore,\n'
    '                    smsGateway = smsGateway,\n'
    '                    callHistoryGateway = callHistoryGateway,\n'
    '                    meetingStore = meetingStore,\n'
    '                    buildGroundBridge = buildGroundBridge,\n'
    '                ),\n',
)

# Daily agenda is calendar-aware so the system prompt receives current local time.
replace_once(
    "plugins/assistant/src/main/java/com/anezium/rokidbus/plugin/assistant/CalendarTools.kt",
    '    DELETE_CALENDAR_EVENT_TOOL_NAME,\n)\n',
    '    DELETE_CALENDAR_EVENT_TOOL_NAME,\n    DAILY_AGENDA_TOOL_NAME,\n)\n',
)

# Hermes text bridge allowlist.
replace_once(
    "plugins/assistant/src/main/java/com/anezium/rokidbus/plugin/assistant/AssistantTool.kt",
    '    CALL_CONTACT_TOOL_NAME,\n)\n',
    '    CALL_CONTACT_TOOL_NAME,\n'
    '    REDIAL_LAST_CALL_TOOL_NAME,\n'
    '    SEND_SMS_TOOL_NAME,\n'
    '    DAILY_AGENDA_TOOL_NAME,\n'
    '    ENGINEERING_CALC_TOOL_NAME,\n'
    '    LIST_NOTIFICATIONS_TOOL_NAME,\n'
    '    DISMISS_NOTIFICATION_TOOL_NAME,\n'
    '    MEETING_START_TOOL_NAME,\n'
    '    MEETING_ADD_TOOL_NAME,\n'
    '    MEETING_FINISH_TOOL_NAME,\n'
    '    BUILDGROUND_QUERY_TOOL_NAME,\n'
    ')\n',
)

# ---------------------------------------------------------------------------
# Agent policy: explicit actions, meeting capture, notifications and visual follow-ups.

policy = "plugins/assistant/src/main/java/com/anezium/rokidbus/plugin/assistant/NexusAgentPolicy.kt"
replace_once(
    policy,
    '        val calendarToolsAvailable = availableToolNames.any(CALENDAR_TOOL_NAMES::contains)\n',
    '        val calendarToolsAvailable = availableToolNames.any(CALENDAR_TOOL_NAMES::contains)\n'
    '        val communicationToolsAvailable = availableToolNames.any(COMMUNICATION_TOOL_NAMES::contains)\n'
    '        val notificationToolsAvailable = availableToolNames.any(NOTIFICATION_TOOL_NAMES::contains)\n'
    '        val meetingToolsAvailable = availableToolNames.any(MEETING_TOOL_NAMES::contains)\n',
)
replace_once(
    policy,
    '                        "about what was seen, say so plainly and offer to look again.\\n",\n'
    '                )\n',
    '                        "about what was seen, say so plainly and offer to look again.\\n",\n'
    '                )\n'
    '                append(\n'
    '                    "- In a conversational visual follow-up such as ‘what about this?’, ‘а вот это?’, " +\n'
    '                        "‘эта деталь?’ or another deictic reference to what the wearer is looking at now, " +\n'
    '                        "take a fresh photo when the current view is needed. If they explicitly refer to " +\n'
    '                        "the previous photo instead, use conversation context and do not recapture.\\n",\n'
    '                )\n',
)
replace_once(
    policy,
    '            if (DELETE_CALENDAR_EVENT_TOOL_NAME in availableToolNames) {\n',
    '            if (communicationToolsAvailable) {\n'
    '                append(\n'
    '                    "- Place a call, redial, or send an SMS only when the user explicitly asks for that " +\n'
    '                        "action. Never invent a recipient, phone number, contact detail, or SMS body. If " +\n'
    '                        "the tool reports ambiguity, ask the wearer to choose.\\n",\n'
    '                )\n'
    '            }\n'
    '            if (notificationToolsAvailable) {\n'
    '                append(\n'
    '                    "- You may read and summarize notifications exposed by list_notifications and dismiss " +\n'
    '                        "one only after an explicit request. This is not Relay: never claim you replied to " +\n'
    '                        "a notification or sent a messenger response. You may draft a reply in text.\\n",\n'
    '                )\n'
    '            }\n'
    '            if (meetingToolsAvailable) {\n'
    '                append(\n'
    '                    "- When the user explicitly says to start a meeting, call meeting_start. After it starts, " +\n'
    '                        "treat subsequent dictated meeting content as notes and call meeting_add for each " +\n'
    '                        "chunk, replying only very briefly so Conversation mode can continue. When the user " +\n'
    '                        "says the meeting is finished, call meeting_finish and turn its transcript into a " +\n'
    '                        "concise protocol with facts, decisions, tasks, owners and deadlines when present. " +\n'
    '                        "Do not invent missing owners or deadlines.\\n",\n'
    '                )\n'
    '            }\n'
    '            if (DELETE_CALENDAR_EVENT_TOOL_NAME in availableToolNames) {\n',
)

# Policy allowlist test is patched by the phone-call generator first.
test_policy = "plugins/assistant/src/test/java/com/anezium/rokidbus/plugin/assistant/NexusAgentPolicyTest.kt"
replace_once(
    test_policy,
    '                CALL_CONTACT_TOOL_NAME,\n            ),\n',
    '                CALL_CONTACT_TOOL_NAME,\n'
    '                REDIAL_LAST_CALL_TOOL_NAME,\n'
    '                SEND_SMS_TOOL_NAME,\n'
    '                DAILY_AGENDA_TOOL_NAME,\n'
    '                ENGINEERING_CALC_TOOL_NAME,\n'
    '                LIST_NOTIFICATIONS_TOOL_NAME,\n'
    '                DISMISS_NOTIFICATION_TOOL_NAME,\n'
    '                MEETING_START_TOOL_NAME,\n'
    '                MEETING_ADD_TOOL_NAME,\n'
    '                MEETING_FINISH_TOOL_NAME,\n'
    '                BUILDGROUND_QUERY_TOOL_NAME,\n'
    '            ),\n',
)

# ---------------------------------------------------------------------------
# Main feature pack tools.

write(
    "plugins/assistant/src/main/java/com/anezium/rokidbus/plugin/assistant/AssistantMvpTools.kt",
    r'''package com.anezium.rokidbus.plugin.assistant

import android.Manifest
import android.content.Context
import android.content.pm.PackageManager
import android.net.Uri
import android.os.Bundle
import android.provider.CallLog
import android.provider.ContactsContract
import android.telecom.TelecomManager
import android.telephony.SmsManager
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.time.Instant
import java.time.LocalDate
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import java.util.Locale
import kotlin.math.PI
import kotlin.math.round

internal const val REDIAL_LAST_CALL_TOOL_NAME = "redial_last_call"
internal const val SEND_SMS_TOOL_NAME = "send_sms"
internal const val DAILY_AGENDA_TOOL_NAME = "daily_agenda"
internal const val ENGINEERING_CALC_TOOL_NAME = "engineering_calc"
internal const val LIST_NOTIFICATIONS_TOOL_NAME = "list_notifications"
internal const val DISMISS_NOTIFICATION_TOOL_NAME = "dismiss_notification"
internal const val MEETING_START_TOOL_NAME = "meeting_start"
internal const val MEETING_ADD_TOOL_NAME = "meeting_add"
internal const val MEETING_FINISH_TOOL_NAME = "meeting_finish"
internal const val BUILDGROUND_QUERY_TOOL_NAME = "buildground_query"

internal val COMMUNICATION_TOOL_NAMES = setOf(
    CALL_CONTACT_TOOL_NAME,
    REDIAL_LAST_CALL_TOOL_NAME,
    SEND_SMS_TOOL_NAME,
)
internal val NOTIFICATION_TOOL_NAMES = setOf(
    LIST_NOTIFICATIONS_TOOL_NAME,
    DISMISS_NOTIFICATION_TOOL_NAME,
)
internal val MEETING_TOOL_NAMES = setOf(
    MEETING_START_TOOL_NAME,
    MEETING_ADD_TOOL_NAME,
    MEETING_FINISH_TOOL_NAME,
)

internal fun assistantMvpTools(
    calendarGateway: AssistantCalendarGateway,
    reminderStore: AssistantReminderStore,
    smsGateway: AssistantSmsGateway,
    callHistoryGateway: AssistantCallHistoryGateway,
    meetingStore: AssistantMeetingStore,
    buildGroundBridge: BuildGroundDataBridge,
    epochClock: () -> Long = System::currentTimeMillis,
    zoneId: () -> ZoneId = { ZoneId.systemDefault() },
): List<AssistantToolDefinition> = listOf(
    RedialLastCallTool(callHistoryGateway),
    SendSmsTool(smsGateway),
    DailyAgendaTool(calendarGateway, reminderStore, epochClock, zoneId),
    EngineeringCalcTool(),
    ListNotificationsTool(epochClock, zoneId),
    DismissNotificationTool(),
    MeetingStartTool(meetingStore, epochClock, zoneId),
    MeetingAddTool(meetingStore),
    MeetingFinishTool(meetingStore, epochClock, zoneId),
    BuildGroundQueryTool(buildGroundBridge),
)

// ---------------------------------------------------------------------------
// SMS

internal data class AssistantSmsContact(
    val contactId: Long,
    val displayName: String,
    val number: String,
    val label: String,
    val isPrimary: Boolean,
    val isSuperPrimary: Boolean,
)

internal interface AssistantSmsGateway {
    fun canReadContacts(): Boolean
    fun canSendSms(): Boolean
    fun contacts(): List<AssistantSmsContact>
    fun send(number: String, message: String): Boolean
}

internal class AndroidSmsGateway(context: Context) : AssistantSmsGateway {
    private val appContext = context.applicationContext
    private val resolver = appContext.contentResolver

    override fun canReadContacts(): Boolean =
        appContext.checkSelfPermission(Manifest.permission.READ_CONTACTS) == PackageManager.PERMISSION_GRANTED

    override fun canSendSms(): Boolean =
        appContext.checkSelfPermission(Manifest.permission.SEND_SMS) == PackageManager.PERMISSION_GRANTED

    override fun contacts(): List<AssistantSmsContact> {
        if (!canReadContacts()) return emptyList()
        val projection = arrayOf(
            ContactsContract.CommonDataKinds.Phone.CONTACT_ID,
            ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME,
            ContactsContract.CommonDataKinds.Phone.NUMBER,
            ContactsContract.CommonDataKinds.Phone.TYPE,
            ContactsContract.CommonDataKinds.Phone.LABEL,
            ContactsContract.CommonDataKinds.Phone.IS_PRIMARY,
            ContactsContract.CommonDataKinds.Phone.IS_SUPER_PRIMARY,
        )
        return resolver.query(
            ContactsContract.CommonDataKinds.Phone.CONTENT_URI,
            projection,
            null,
            null,
            ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME + " COLLATE LOCALIZED ASC",
        )?.use { cursor ->
            val idCol = cursor.getColumnIndexOrThrow(ContactsContract.CommonDataKinds.Phone.CONTACT_ID)
            val nameCol = cursor.getColumnIndexOrThrow(ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME)
            val numberCol = cursor.getColumnIndexOrThrow(ContactsContract.CommonDataKinds.Phone.NUMBER)
            val typeCol = cursor.getColumnIndexOrThrow(ContactsContract.CommonDataKinds.Phone.TYPE)
            val labelCol = cursor.getColumnIndexOrThrow(ContactsContract.CommonDataKinds.Phone.LABEL)
            val primaryCol = cursor.getColumnIndexOrThrow(ContactsContract.CommonDataKinds.Phone.IS_PRIMARY)
            val superCol = cursor.getColumnIndexOrThrow(ContactsContract.CommonDataKinds.Phone.IS_SUPER_PRIMARY)
            buildList {
                while (cursor.moveToNext()) {
                    val name = cursor.getString(nameCol).orEmpty().trim()
                    val number = cursor.getString(numberCol).orEmpty().trim()
                    if (name.isBlank() || number.isBlank()) continue
                    add(
                        AssistantSmsContact(
                            contactId = cursor.getLong(idCol),
                            displayName = name,
                            number = number,
                            label = ContactsContract.CommonDataKinds.Phone.getTypeLabel(
                                appContext.resources,
                                cursor.getInt(typeCol),
                                cursor.getString(labelCol),
                            ).toString().ifBlank { "phone" },
                            isPrimary = cursor.getInt(primaryCol) == 1,
                            isSuperPrimary = cursor.getInt(superCol) == 1,
                        ),
                    )
                }
            }
        }.orEmpty()
    }

    @Suppress("DEPRECATION")
    override fun send(number: String, message: String): Boolean {
        if (!canSendSms()) return false
        return runCatching {
            val manager = SmsManager.getDefault()
            val parts = manager.divideMessage(message)
            if (parts.size <= 1) {
                manager.sendTextMessage(number, null, message, null, null)
            } else {
                manager.sendMultipartTextMessage(number, null, parts, null, null)
            }
        }.isSuccess
    }
}

internal class SendSmsTool(
    private val gateway: AssistantSmsGateway,
) : TextAssistantTool() {
    override val name = SEND_SMS_TOOL_NAME
    override val description =
        "Send a real SMS from the phone only when the user explicitly asks to text or send SMS. " +
            "query is the contact name, message is the exact intended message, and detail is an optional " +
            "surname, phone label, or last digits used to resolve ambiguity. Never send if the recipient is ambiguous."
    override val parametersSchema = AssistantToolJsonSchema(
        """{"type":"object","properties":{"query":{"type":"string","minLength":1},"message":{"type":"string","minLength":1,"maxLength":2000},"detail":{"type":["string","null"]}},"required":["query","message","detail"],"additionalProperties":false}""",
    )
    override val sideEffecting = true
    override val progressLabel = "Sending SMS…"
    override val retiresProgressOnSuccess = true
    override val executionFailureCode = "sms_send_failed"

    override fun validate(argumentsJson: String): AssistantToolValidation {
        val args = strictMvpArguments(argumentsJson, setOf("query", "message", "detail"))
            ?: return AssistantToolValidation.Invalid()
        val query = args.stringValue("query")?.trim().orEmpty()
        val message = args.stringValue("message")?.trim().orEmpty()
        if (query.isBlank() || message.isBlank() || message.length > 2000) {
            return AssistantToolValidation.Invalid()
        }
        val detail = args.stringValue("detail")?.trim()?.ifBlank { null }
        return AssistantToolValidation.Valid(
            JSONObject().put("query", query).put("message", message)
                .put("detail", detail ?: JSONObject.NULL),
        )
    }

    override suspend fun execute(
        call: AssistantToolCall,
        arguments: JSONObject,
    ): AssistantToolResult = withContext(Dispatchers.IO) {
        if (!gateway.canReadContacts() || !gateway.canSendSms()) {
            return@withContext AssistantToolResult.Error(
                "sms_permission_required",
                JSONObject().put("message", "Grant Contacts and SMS access in Assistant settings.").toString(),
            )
        }
        val query = arguments.getString("query")
        val detail = arguments.stringValue("detail")
        val candidates = resolveSmsContacts(query, detail, gateway.contacts())
        if (candidates.size != 1) {
            return@withContext AssistantToolResult.Error(
                if (candidates.isEmpty()) "contact_not_found" else "ambiguous",
                JSONObject()
                    .put("query", query)
                    .put("candidates", JSONArray().apply {
                        candidates.take(8).forEach { candidate ->
                            put(
                                JSONObject()
                                    .put("name", candidate.displayName)
                                    .put("label", candidate.label)
                                    .put("last4", phoneDigits(candidate.number).takeLast(4)),
                            )
                        }
                    })
                    .toString(),
            )
        }
        val selected = candidates.single()
        if (!gateway.send(selected.number, arguments.getString("message"))) {
            return@withContext AssistantToolResult.Error(executionFailureCode)
        }
        AssistantToolResult.Json(
            JSONObject()
                .put("sent", true)
                .put("contact", selected.displayName)
                .put("label", selected.label)
                .put("last4", phoneDigits(selected.number).takeLast(4))
                .toString(),
        )
    }
}

internal fun resolveSmsContacts(
    query: String,
    detail: String?,
    contacts: List<AssistantSmsContact>,
): List<AssistantSmsContact> {
    val queryTokens = contactTokens(query)
    if (queryTokens.isEmpty()) return emptyList()
    val scored = contacts.mapNotNull { contact ->
        val nameTokens = contactTokens(contact.displayName)
        val score = queryTokens.sumOf { queryToken ->
            nameTokens.minOfOrNull { nameToken -> contactTokenDistance(queryToken, nameToken) } ?: 99
        }
        if (score >= 20) null else contact to score
    }
    if (scored.isEmpty()) return emptyList()
    val best = scored.minOf { it.second }
    var candidates = scored.filter { it.second == best }.map { it.first }
    if (!detail.isNullOrBlank()) {
        val normalizedDetail = normalizeContact(detail)
        val detailDigits = phoneDigits(detail)
        candidates = candidates.filter { contact ->
            normalizeContact(contact.displayName).contains(normalizedDetail) ||
                normalizeContact(contact.label).contains(normalizedDetail) ||
                detailDigits.length >= 3 && phoneDigits(contact.number).endsWith(detailDigits)
        }
    }
    val byContact = candidates.groupBy(AssistantSmsContact::contactId)
    return byContact.values.flatMap { entries ->
        val preferred = entries.filter { it.isSuperPrimary || it.isPrimary }
        when {
            preferred.size == 1 -> preferred
            entries.size == 1 -> entries
            else -> entries
        }
    }.distinctBy { it.contactId to phoneDigits(it.number) }
}

private fun contactTokens(value: String): List<String> =
    normalizeContact(value).split(' ').filter(String::isNotBlank)

private fun normalizeContact(value: String): String = value.lowercase(Locale.ROOT)
    .replace('ё', 'е')
    .replace(Regex("[^\\p{L}\\p{N}]+"), " ")
    .trim()

private fun contactTokenDistance(a: String, b: String): Int {
    if (a == b) return 0
    if (a.startsWith(b) || b.startsWith(a)) return 1
    val common = a.zip(b).takeWhile { (x, y) -> x == y }.size
    if (common >= (minOf(a.length, b.length) - 2).coerceAtLeast(3)) return 2
    return 20
}

private fun phoneDigits(value: String): String = value.filter(Char::isDigit)

// ---------------------------------------------------------------------------
// Last-call redial

internal data class AssistantCallHistoryEntry(
    val number: String,
    val cachedName: String?,
    val timestampMs: Long,
)

internal interface AssistantCallHistoryGateway {
    fun canReadCallLog(): Boolean
    fun canPlaceCalls(): Boolean
    fun lastCall(): AssistantCallHistoryEntry?
    fun placeCall(number: String): Boolean
}

internal class AndroidCallHistoryGateway(context: Context) : AssistantCallHistoryGateway {
    private val appContext = context.applicationContext

    override fun canReadCallLog(): Boolean =
        appContext.checkSelfPermission(Manifest.permission.READ_CALL_LOG) == PackageManager.PERMISSION_GRANTED

    override fun canPlaceCalls(): Boolean =
        appContext.checkSelfPermission(Manifest.permission.CALL_PHONE) == PackageManager.PERMISSION_GRANTED

    override fun lastCall(): AssistantCallHistoryEntry? {
        if (!canReadCallLog()) return null
        val resolver = appContext.contentResolver
        val projection = arrayOf(
            CallLog.Calls.NUMBER,
            CallLog.Calls.CACHED_NAME,
            CallLog.Calls.DATE,
        )
        val selection = "${CallLog.Calls.TYPE} IN (?,?,?,?)"
        val args = arrayOf(
            CallLog.Calls.INCOMING_TYPE.toString(),
            CallLog.Calls.OUTGOING_TYPE.toString(),
            CallLog.Calls.MISSED_TYPE.toString(),
            CallLog.Calls.REJECTED_TYPE.toString(),
        )
        return resolver.query(
            CallLog.Calls.CONTENT_URI,
            projection,
            selection,
            args,
            "${CallLog.Calls.DATE} DESC",
        )?.use { cursor ->
            if (!cursor.moveToFirst()) return@use null
            val number = cursor.getString(cursor.getColumnIndexOrThrow(CallLog.Calls.NUMBER)).orEmpty()
            if (number.isBlank()) return@use null
            AssistantCallHistoryEntry(
                number = number,
                cachedName = cursor.getString(cursor.getColumnIndexOrThrow(CallLog.Calls.CACHED_NAME)),
                timestampMs = cursor.getLong(cursor.getColumnIndexOrThrow(CallLog.Calls.DATE)),
            )
        }
    }

    override fun placeCall(number: String): Boolean {
        if (!canPlaceCalls()) return false
        val telecom = appContext.getSystemService(TelecomManager::class.java) ?: return false
        return runCatching {
            telecom.placeCall(Uri.fromParts("tel", number, null), Bundle.EMPTY)
        }.isSuccess
    }
}

internal class RedialLastCallTool(
    private val gateway: AssistantCallHistoryGateway,
) : TextAssistantTool() {
    override val name = REDIAL_LAST_CALL_TOOL_NAME
    override val description =
        "Call back the most recent real phone call only when the user explicitly says redial, " +
            "call back the last caller, ‘перезвони последнему’, or equivalent."
    override val parametersSchema = EMPTY_MVP_SCHEMA
    override val sideEffecting = true
    override val progressLabel = "Calling back…"
    override val retiresProgressOnSuccess = true
    override val executionFailureCode = "redial_failed"

    override fun validate(argumentsJson: String): AssistantToolValidation =
        emptyMvpArguments(argumentsJson)

    override suspend fun execute(
        call: AssistantToolCall,
        arguments: JSONObject,
    ): AssistantToolResult = withContext(Dispatchers.IO) {
        if (!gateway.canReadCallLog() || !gateway.canPlaceCalls()) {
            return@withContext AssistantToolResult.Error(
                "call_log_permission_required",
                JSONObject().put("message", "Grant Phone and Call history access in Assistant settings.").toString(),
            )
        }
        val last = gateway.lastCall()
            ?: return@withContext AssistantToolResult.Error("no_recent_call")
        if (!gateway.placeCall(last.number)) {
            return@withContext AssistantToolResult.Error(executionFailureCode)
        }
        AssistantToolResult.Json(
            JSONObject()
                .put("calling", true)
                .put("contact", last.cachedName ?: JSONObject.NULL)
                .put("last4", phoneDigits(last.number).takeLast(4))
                .put("previous_call_at", last.timestampMs)
                .toString(),
        )
    }
}

// ---------------------------------------------------------------------------
// Today's agenda: real Android calendar + Nexus reminders.

internal class DailyAgendaTool(
    private val calendar: AssistantCalendarGateway,
    private val reminders: AssistantReminderStore,
    private val epochClock: () -> Long = System::currentTimeMillis,
    private val zoneId: () -> ZoneId = { ZoneId.systemDefault() },
) : TextAssistantTool() {
    override val name = DAILY_AGENDA_TOOL_NAME
    override val description =
        "Return the wearer's full agenda for one local calendar date, including real phone " +
            "calendar events and pending Nexus reminders. Use this for ‘what do I have today?’, " +
            "‘что у меня сегодня?’, tomorrow, or another explicit date."
    override val parametersSchema = AssistantToolJsonSchema(
        """{"type":"object","properties":{"date":{"type":["string","null"],"description":"ISO local date YYYY-MM-DD; null means today"}},"required":["date"],"additionalProperties":false}""",
    )
    override val sideEffecting = false
    override val progressLabel = "Checking today…"

    override fun validate(argumentsJson: String): AssistantToolValidation {
        val args = strictMvpArguments(argumentsJson, setOf("date"))
            ?: return AssistantToolValidation.Invalid()
        val value = args.stringValue("date")
        if (value != null && runCatching { LocalDate.parse(value) }.isFailure) {
            return AssistantToolValidation.Invalid(AssistantToolResult.Error("invalid_agenda_date"))
        }
        return AssistantToolValidation.Valid(args)
    }

    override suspend fun execute(
        call: AssistantToolCall,
        arguments: JSONObject,
    ): AssistantToolResult = withContext(Dispatchers.IO) {
        if (!calendar.canReadCalendar()) {
            return@withContext AssistantToolResult.Error(
                TOOL_ERROR_CALENDAR_PERMISSION_REQUIRED,
                JSONObject().put("message", "Grant Calendar access in Assistant settings.").toString(),
            )
        }
        val zone = zoneId()
        val date = arguments.stringValue("date")?.let(LocalDate::parse)
            ?: Instant.ofEpochMilli(epochClock()).atZone(zone).toLocalDate()
        val start = date.atStartOfDay(zone).toInstant().toEpochMilli()
        val end = date.plusDays(1).atStartOfDay(zone).toInstant().toEpochMilli()
        val events = calendar.instances(start, end, 51).take(50)
        val pending = reminders.pending().filter { it.epochMillis in start until end }.take(30)
        AssistantToolResult.Json(
            JSONObject()
                .put("date", date.toString())
                .put("time_zone", zone.id)
                .put("events", JSONArray().apply {
                    events.forEach { event ->
                        put(
                            JSONObject()
                                .put("title", event.title)
                                .put("start", formatLocal(event.startMillis, zone))
                                .put("all_day", event.allDay)
                                .put("location", event.location ?: JSONObject.NULL),
                        )
                    }
                })
                .put("reminders", JSONArray().apply {
                    pending.forEach { reminder ->
                        put(
                            JSONObject()
                                .put("label", reminder.label)
                                .put("at", formatLocal(reminder.epochMillis, zone))
                                .put("kind", reminder.kind.wireValue),
                        )
                    }
                })
                .put("event_count", events.size)
                .put("reminder_count", pending.size)
                .toString(),
        )
    }
}

private fun formatLocal(epochMs: Long, zone: ZoneId): String =
    Instant.ofEpochMilli(epochMs).atZone(zone).format(DateTimeFormatter.ISO_OFFSET_DATE_TIME)

// ---------------------------------------------------------------------------
// Deterministic engineering calculator.

internal class EngineeringCalcTool : TextAssistantTool() {
    override val name = ENGINEERING_CALC_TOOL_NAME
    override val description =
        "Deterministic engineering calculator for BuildGround-style field calculations. " +
            "Supported operations: pipe_mass (steel pipe by OD, wall and length), rebar_mass, " +
            "cylinder_volume (pile/concrete cylinder), circle_area, and unit_convert. Use metric inputs."
    override val parametersSchema = AssistantToolJsonSchema(
        """{"type":"object","properties":{"operation":{"type":"string","enum":["pipe_mass","rebar_mass","cylinder_volume","circle_area","unit_convert"]},"outer_diameter_mm":{"type":["number","null"]},"wall_mm":{"type":["number","null"]},"diameter_mm":{"type":["number","null"]},"length_m":{"type":["number","null"]},"quantity":{"type":["number","null"],"default":1},"value":{"type":["number","null"]},"from_unit":{"type":["string","null"]},"to_unit":{"type":["string","null"]}},"required":["operation","outer_diameter_mm","wall_mm","diameter_mm","length_m","quantity","value","from_unit","to_unit"],"additionalProperties":false}""",
    )
    override val sideEffecting = false
    override val progressLabel = "Calculating…"

    override fun validate(argumentsJson: String): AssistantToolValidation {
        val allowed = setOf(
            "operation", "outer_diameter_mm", "wall_mm", "diameter_mm", "length_m",
            "quantity", "value", "from_unit", "to_unit",
        )
        val args = strictMvpArguments(argumentsJson, allowed)
            ?: return AssistantToolValidation.Invalid()
        val op = args.stringValue("operation")
        if (op !in ENGINEERING_OPERATIONS) return AssistantToolValidation.Invalid()
        return AssistantToolValidation.Valid(args)
    }

    override suspend fun execute(
        call: AssistantToolCall,
        arguments: JSONObject,
    ): AssistantToolResult = calculateEngineering(arguments)
}

internal fun calculateEngineering(arguments: JSONObject): AssistantToolResult {
    fun n(name: String): Double? = arguments.numberValue(name)
    fun positive(name: String): Double? = n(name)?.takeIf { it.isFinite() && it > 0.0 }
    val quantity = n("quantity")?.takeIf { it.isFinite() && it > 0.0 } ?: 1.0
    return when (arguments.stringValue("operation")) {
        "pipe_mass" -> {
            val d = positive("outer_diameter_mm")
                ?: return AssistantToolResult.Error("invalid_engineering_inputs")
            val t = positive("wall_mm")
                ?: return AssistantToolResult.Error("invalid_engineering_inputs")
            val length = positive("length_m")
                ?: return AssistantToolResult.Error("invalid_engineering_inputs")
            if (2.0 * t >= d) return AssistantToolResult.Error("invalid_engineering_inputs")
            val outer = d / 1000.0
            val inner = (d - 2.0 * t) / 1000.0
            val kgPerM = PI / 4.0 * (outer * outer - inner * inner) * STEEL_DENSITY_KG_M3
            val totalKg = kgPerM * length * quantity
            jsonCalc(
                "operation" to "pipe_mass",
                "kg_per_m" to round3(kgPerM),
                "total_kg" to round3(totalKg),
                "total_t" to round3(totalKg / 1000.0),
            )
        }
        "rebar_mass" -> {
            val d = positive("diameter_mm")
                ?: return AssistantToolResult.Error("invalid_engineering_inputs")
            val length = positive("length_m")
                ?: return AssistantToolResult.Error("invalid_engineering_inputs")
            val kgPerM = PI / 4.0 * (d / 1000.0) * (d / 1000.0) * STEEL_DENSITY_KG_M3
            val totalKg = kgPerM * length * quantity
            jsonCalc(
                "operation" to "rebar_mass",
                "kg_per_m" to round3(kgPerM),
                "total_kg" to round3(totalKg),
                "total_t" to round3(totalKg / 1000.0),
            )
        }
        "cylinder_volume" -> {
            val d = positive("diameter_mm")
                ?: return AssistantToolResult.Error("invalid_engineering_inputs")
            val length = positive("length_m")
                ?: return AssistantToolResult.Error("invalid_engineering_inputs")
            val volume = PI / 4.0 * (d / 1000.0) * (d / 1000.0) * length * quantity
            jsonCalc("operation" to "cylinder_volume", "volume_m3" to round3(volume))
        }
        "circle_area" -> {
            val d = positive("diameter_mm")
                ?: return AssistantToolResult.Error("invalid_engineering_inputs")
            val area = PI / 4.0 * (d / 1000.0) * (d / 1000.0) * quantity
            jsonCalc("operation" to "circle_area", "area_m2" to round3(area))
        }
        "unit_convert" -> {
            val value = n("value")?.takeIf(Double::isFinite)
                ?: return AssistantToolResult.Error("invalid_engineering_inputs")
            val from = arguments.stringValue("from_unit")?.lowercase(Locale.ROOT)
                ?: return AssistantToolResult.Error("invalid_engineering_inputs")
            val to = arguments.stringValue("to_unit")?.lowercase(Locale.ROOT)
                ?: return AssistantToolResult.Error("invalid_engineering_inputs")
            val converted = convertUnit(value, from, to)
                ?: return AssistantToolResult.Error("unsupported_unit_conversion")
            jsonCalc(
                "operation" to "unit_convert",
                "value" to round3(converted),
                "unit" to to,
            )
        }
        else -> AssistantToolResult.Error("invalid_engineering_inputs")
    }
}

private fun convertUnit(value: Double, from: String, to: String): Double? {
    if (from == to) return value
    return when (from to to) {
        "mm" to "m" -> value / 1000.0
        "m" to "mm" -> value * 1000.0
        "kg" to "t" -> value / 1000.0
        "t" to "kg" -> value * 1000.0
        "cm" to "m" -> value / 100.0
        "m" to "cm" -> value * 100.0
        "l" to "m3" -> value / 1000.0
        "m3" to "l" -> value * 1000.0
        else -> null
    }
}

private fun jsonCalc(vararg pairs: Pair<String, Any>): AssistantToolResult.Json =
    AssistantToolResult.Json(JSONObject().apply { pairs.forEach { (k, v) -> put(k, v) } }.toString())

private fun round3(value: Double): Double = round(value * 1000.0) / 1000.0
private const val STEEL_DENSITY_KG_M3 = 7850.0
private val ENGINEERING_OPERATIONS = setOf(
    "pipe_mass", "rebar_mass", "cylinder_volume", "circle_area", "unit_convert",
)

// ---------------------------------------------------------------------------
// Meeting session. Conversation Mode provides the repeated capture loop; this store only records
// explicit chunks, avoiding a hidden always-on microphone.

internal data class AssistantMeetingSnapshot(
    val title: String,
    val startedAtMs: Long,
    val chunks: List<String>,
)

internal class AssistantMeetingStore(
    private val maxChars: Int = 20_000,
) {
    private var title: String? = null
    private var startedAtMs: Long = 0L
    private val chunks = mutableListOf<String>()

    @Synchronized
    fun start(newTitle: String, nowMs: Long): AssistantMeetingSnapshot? {
        if (title != null) return null
        title = newTitle.trim().ifBlank { "Meeting" }.take(120)
        startedAtMs = nowMs
        chunks.clear()
        return snapshot()
    }

    @Synchronized
    fun add(text: String): Boolean {
        if (title == null) return false
        val normalized = text.trim()
        if (normalized.isBlank()) return false
        val current = chunks.sumOf(String::length)
        if (current >= maxChars) return false
        chunks += normalized.take((maxChars - current).coerceAtLeast(0))
        return true
    }

    @Synchronized
    fun finish(): AssistantMeetingSnapshot? {
        if (title == null) return null
        val result = snapshot()
        title = null
        startedAtMs = 0L
        chunks.clear()
        return result
    }

    @Synchronized
    fun active(): Boolean = title != null

    private fun snapshot(): AssistantMeetingSnapshot = AssistantMeetingSnapshot(
        title = title ?: "Meeting",
        startedAtMs = startedAtMs,
        chunks = chunks.toList(),
    )
}

internal class MeetingStartTool(
    private val store: AssistantMeetingStore,
    private val epochClock: () -> Long,
    private val zoneId: () -> ZoneId,
) : TextAssistantTool() {
    override val name = MEETING_START_TOOL_NAME
    override val description =
        "Start a local meeting-note session after the user explicitly asks to begin a meeting or protocol."
    override val parametersSchema = AssistantToolJsonSchema(
        """{"type":"object","properties":{"title":{"type":["string","null"],"maxLength":120}},"required":["title"],"additionalProperties":false}""",
    )
    override val sideEffecting = true
    override val progressLabel = "Starting meeting…"

    override fun validate(argumentsJson: String): AssistantToolValidation {
        val args = strictMvpArguments(argumentsJson, setOf("title"))
            ?: return AssistantToolValidation.Invalid()
        return AssistantToolValidation.Valid(args)
    }

    override suspend fun execute(call: AssistantToolCall, arguments: JSONObject): AssistantToolResult {
        val now = epochClock()
        val snapshot = store.start(arguments.stringValue("title") ?: "Meeting", now)
            ?: return AssistantToolResult.Error("meeting_already_active")
        return AssistantToolResult.Json(
            JSONObject()
                .put("started", true)
                .put("title", snapshot.title)
                .put("started_at", formatLocal(now, zoneId()))
                .put("instruction", "Meeting session is active; add each dictated chunk with meeting_add.")
                .toString(),
        )
    }
}

internal class MeetingAddTool(
    private val store: AssistantMeetingStore,
) : TextAssistantTool() {
    override val name = MEETING_ADD_TOOL_NAME
    override val description =
        "Append one dictated chunk to the active meeting session. Use for factual meeting speech after meeting_start."
    override val parametersSchema = AssistantToolJsonSchema(
        """{"type":"object","properties":{"text":{"type":"string","minLength":1,"maxLength":4000}},"required":["text"],"additionalProperties":false}""",
    )
    override val sideEffecting = true
    override val progressLabel = "Recording meeting note…"

    override fun validate(argumentsJson: String): AssistantToolValidation {
        val args = strictMvpArguments(argumentsJson, setOf("text"))
            ?: return AssistantToolValidation.Invalid()
        if (args.stringValue("text").isNullOrBlank()) return AssistantToolValidation.Invalid()
        return AssistantToolValidation.Valid(args)
    }

    override suspend fun execute(call: AssistantToolCall, arguments: JSONObject): AssistantToolResult {
        if (!store.active()) return AssistantToolResult.Error("meeting_not_active")
        if (!store.add(arguments.getString("text"))) return AssistantToolResult.Error("meeting_notes_full")
        return AssistantToolResult.Json(JSONObject().put("recorded", true).toString())
    }
}

internal class MeetingFinishTool(
    private val store: AssistantMeetingStore,
    private val epochClock: () -> Long,
    private val zoneId: () -> ZoneId,
) : TextAssistantTool() {
    override val name = MEETING_FINISH_TOOL_NAME
    override val description =
        "Finish the active meeting and return its transcript. After this tool succeeds, summarize it as a " +
            "business protocol with facts, decisions, tasks, owners and deadlines only when those are present."
    override val parametersSchema = EMPTY_MVP_SCHEMA
    override val sideEffecting = true
    override val progressLabel = "Finishing protocol…"

    override fun validate(argumentsJson: String): AssistantToolValidation = emptyMvpArguments(argumentsJson)

    override suspend fun execute(call: AssistantToolCall, arguments: JSONObject): AssistantToolResult {
        val snapshot = store.finish() ?: return AssistantToolResult.Error("meeting_not_active")
        return AssistantToolResult.Json(
            JSONObject()
                .put("finished", true)
                .put("title", snapshot.title)
                .put("started_at", formatLocal(snapshot.startedAtMs, zoneId()))
                .put("finished_at", formatLocal(epochClock(), zoneId()))
                .put("chunks", snapshot.chunks.size)
                .put("transcript", snapshot.chunks.joinToString("\n"))
                .toString(),
        )
    }
}

// ---------------------------------------------------------------------------
// Smart notifications. Reading/dismissing lives in AssistantNotificationListenerService; no Relay.

internal class ListNotificationsTool(
    private val epochClock: () -> Long,
    private val zoneId: () -> ZoneId,
) : TextAssistantTool() {
    override val name = LIST_NOTIFICATIONS_TOOL_NAME
    override val description =
        "List recent Android phone notifications so you can summarize what matters. This does not use Relay " +
            "and cannot send messenger replies."
    override val parametersSchema = AssistantToolJsonSchema(
        """{"type":"object","properties":{"hours":{"type":["integer","null"],"minimum":1,"maximum":72,"default":6}},"required":["hours"],"additionalProperties":false}""",
    )
    override val sideEffecting = false
    override val progressLabel = "Checking notifications…"

    override fun validate(argumentsJson: String): AssistantToolValidation {
        val args = strictMvpArguments(argumentsJson, setOf("hours"))
            ?: return AssistantToolValidation.Invalid()
        val hours = args.numberValue("hours")?.toInt() ?: 6
        if (hours !in 1..72) return AssistantToolValidation.Invalid()
        return AssistantToolValidation.Valid(JSONObject().put("hours", hours))
    }

    override suspend fun execute(call: AssistantToolCall, arguments: JSONObject): AssistantToolResult {
        if (!AssistantNotificationInbox.connected()) return notificationAccessError()
        val hours = arguments.getInt("hours")
        val after = epochClock() - hours * 60L * 60L * 1000L
        val zone = zoneId()
        val items = AssistantNotificationInbox.recent(after, 25)
        return AssistantToolResult.Json(
            JSONObject()
                .put("notifications", JSONArray().apply {
                    items.forEach { item ->
                        put(
                            JSONObject()
                                .put("id", item.id)
                                .put("app", item.appName)
                                .put("title", item.title ?: JSONObject.NULL)
                                .put("text", item.text ?: JSONObject.NULL)
                                .put("posted_at", formatLocal(item.postedAtMs, zone))
                                .put("ongoing", item.ongoing),
                        )
                    }
                })
                .put("count", items.size)
                .toString(),
        )
    }
}

internal class DismissNotificationTool : TextAssistantTool() {
    override val name = DISMISS_NOTIFICATION_TOOL_NAME
    override val description =
        "Dismiss one Android notification by exact id, only after the user explicitly asks to dismiss it."
    override val parametersSchema = AssistantToolJsonSchema(
        """{"type":"object","properties":{"id":{"type":"string","minLength":1}},"required":["id"],"additionalProperties":false}""",
    )
    override val sideEffecting = true
    override val progressLabel = "Dismissing notification…"

    override fun validate(argumentsJson: String): AssistantToolValidation {
        val args = strictMvpArguments(argumentsJson, setOf("id"))
            ?: return AssistantToolValidation.Invalid()
        if (args.stringValue("id").isNullOrBlank()) return AssistantToolValidation.Invalid()
        return AssistantToolValidation.Valid(args)
    }

    override suspend fun execute(call: AssistantToolCall, arguments: JSONObject): AssistantToolResult =
        when (AssistantNotificationInbox.dismiss(arguments.getString("id"))) {
            AssistantNotificationDismissResult.DISMISSED ->
                AssistantToolResult.Json(JSONObject().put("dismissed", true).toString())
            AssistantNotificationDismissResult.NOT_FOUND -> AssistantToolResult.Error("notification_not_found")
            AssistantNotificationDismissResult.NOT_CONNECTED -> notificationAccessError()
        }
}

private fun notificationAccessError(): AssistantToolResult.Error = AssistantToolResult.Error(
    "notification_access_required",
    JSONObject().put(
        "message",
        "Enable Assistant under Android Settings > Special app access > Notification access.",
    ).toString(),
)

// ---------------------------------------------------------------------------
// BuildGround Data Layer seam. Disabled now; when a corporate provider is wired, the same tool
// becomes available without changing the model-facing contract.

internal interface BuildGroundDataProvider {
    val configured: Boolean
    suspend fun query(text: String): JSONObject
}

internal class BuildGroundDataBridge private constructor(
    private val provider: BuildGroundDataProvider?,
) {
    fun isConfigured(): Boolean = provider?.configured == true

    suspend fun query(text: String): JSONObject? =
        provider?.takeIf { it.configured }?.query(text)

    companion object {
        fun disabled(): BuildGroundDataBridge = BuildGroundDataBridge(null)
        fun withProvider(provider: BuildGroundDataProvider): BuildGroundDataBridge = BuildGroundDataBridge(provider)
    }
}

internal class BuildGroundQueryTool(
    private val bridge: BuildGroundDataBridge,
) : TextAssistantTool() {
    override val name = BUILDGROUND_QUERY_TOOL_NAME
    override val description =
        "Query the configured BuildGround corporate Data Layer and return structured project/company context."
    override val parametersSchema = AssistantToolJsonSchema(
        """{"type":"object","properties":{"query":{"type":"string","minLength":1,"maxLength":1000}},"required":["query"],"additionalProperties":false}""",
    )
    override val sideEffecting = false
    override val progressLabel = "Checking BuildGround…"

    override fun isAvailable(context: AssistantToolAvailabilityContext): Boolean =
        super.isAvailable(context) && bridge.isConfigured()

    override fun validate(argumentsJson: String): AssistantToolValidation {
        val args = strictMvpArguments(argumentsJson, setOf("query"))
            ?: return AssistantToolValidation.Invalid()
        if (args.stringValue("query").isNullOrBlank()) return AssistantToolValidation.Invalid()
        return AssistantToolValidation.Valid(args)
    }

    override suspend fun execute(call: AssistantToolCall, arguments: JSONObject): AssistantToolResult {
        val result = bridge.query(arguments.getString("query"))
            ?: return AssistantToolResult.Error("buildground_data_not_configured")
        return AssistantToolResult.Json(result.toString())
    }
}

// ---------------------------------------------------------------------------
// Shared validation helpers.

private val EMPTY_MVP_SCHEMA = AssistantToolJsonSchema(
    """{"type":"object","properties":{},"required":[],"additionalProperties":false}""",
)

private fun emptyMvpArguments(argumentsJson: String): AssistantToolValidation {
    val args = strictMvpArguments(argumentsJson, emptySet())
        ?: return AssistantToolValidation.Invalid()
    return AssistantToolValidation.Valid(args)
}

private fun strictMvpArguments(argumentsJson: String, allowed: Set<String>): JSONObject? {
    val args = runCatching { JSONObject(argumentsJson.ifBlank { "{}" }) }.getOrNull() ?: return null
    val keys = mutableSetOf<String>()
    val iterator = args.keys()
    while (iterator.hasNext()) keys += iterator.next()
    return args.takeIf { keys.all(allowed::contains) }
}

private fun JSONObject.stringValue(name: String): String? =
    if (!has(name) || isNull(name)) null else opt(name) as? String

private fun JSONObject.numberValue(name: String): Double? =
    if (!has(name) || isNull(name)) null else (opt(name) as? Number)?.toDouble()
''',
)

# ---------------------------------------------------------------------------
# Notification listener implementation (independent from Relay).

write(
    "plugins/assistant/src/main/java/com/anezium/rokidbus/plugin/assistant/AssistantNotificationListenerService.kt",
    r'''package com.anezium.rokidbus.plugin.assistant

import android.app.Notification
import android.service.notification.NotificationListenerService
import android.service.notification.StatusBarNotification
import java.util.LinkedHashMap

internal data class AssistantNotificationItem(
    val id: String,
    val key: String,
    val appName: String,
    val packageName: String,
    val title: String?,
    val text: String?,
    val postedAtMs: Long,
    val ongoing: Boolean,
)

internal enum class AssistantNotificationDismissResult {
    DISMISSED,
    NOT_FOUND,
    NOT_CONNECTED,
}

internal object AssistantNotificationInbox {
    private const val MAX_ITEMS = 80
    private val items = LinkedHashMap<String, AssistantNotificationItem>()
    @Volatile private var service: AssistantNotificationListenerService? = null

    @Synchronized
    fun attach(listener: AssistantNotificationListenerService) {
        service = listener
    }

    @Synchronized
    fun detach(listener: AssistantNotificationListenerService) {
        if (service === listener) service = null
    }

    fun connected(): Boolean = service != null

    @Synchronized
    fun upsert(item: AssistantNotificationItem) {
        items[item.id] = item
        while (items.size > MAX_ITEMS) {
            val firstKey = items.keys.firstOrNull() ?: break
            items.remove(firstKey)
        }
    }

    @Synchronized
    fun removeByKey(key: String) {
        val id = items.values.firstOrNull { it.key == key }?.id ?: return
        items.remove(id)
    }

    @Synchronized
    fun recent(afterMs: Long, limit: Int): List<AssistantNotificationItem> =
        items.values.asSequence()
            .filter { it.postedAtMs >= afterMs }
            .sortedByDescending(AssistantNotificationItem::postedAtMs)
            .take(limit.coerceIn(1, 50))
            .toList()

    @Synchronized
    fun dismiss(id: String): AssistantNotificationDismissResult {
        val listener = service ?: return AssistantNotificationDismissResult.NOT_CONNECTED
        val item = items[id] ?: return AssistantNotificationDismissResult.NOT_FOUND
        return runCatching {
            listener.cancelNotification(item.key)
            items.remove(id)
            AssistantNotificationDismissResult.DISMISSED
        }.getOrElse { AssistantNotificationDismissResult.NOT_CONNECTED }
    }
}

class AssistantNotificationListenerService : NotificationListenerService() {
    override fun onListenerConnected() {
        super.onListenerConnected()
        AssistantNotificationInbox.attach(this)
        activeNotifications.orEmpty().forEach(::capture)
    }

    override fun onListenerDisconnected() {
        AssistantNotificationInbox.detach(this)
        super.onListenerDisconnected()
    }

    override fun onNotificationPosted(sbn: StatusBarNotification?) {
        sbn?.let(::capture)
    }

    override fun onNotificationRemoved(sbn: StatusBarNotification?) {
        sbn?.let { AssistantNotificationInbox.removeByKey(it.key) }
    }

    private fun capture(sbn: StatusBarNotification) {
        if (sbn.packageName == packageName) return
        val notification = sbn.notification ?: return
        val extras = notification.extras
        val title = extras.getCharSequence(Notification.EXTRA_TITLE)?.toString()?.trim()?.takeIf(String::isNotBlank)
        val text = (
            extras.getCharSequence(Notification.EXTRA_BIG_TEXT)
                ?: extras.getCharSequence(Notification.EXTRA_TEXT)
                ?: extras.getCharSequence(Notification.EXTRA_SUB_TEXT)
            )?.toString()?.trim()?.takeIf(String::isNotBlank)
        if (title == null && text == null) return
        val appName = runCatching {
            val info = packageManager.getApplicationInfo(sbn.packageName, 0)
            packageManager.getApplicationLabel(info).toString()
        }.getOrDefault(sbn.packageName)
        AssistantNotificationInbox.upsert(
            AssistantNotificationItem(
                id = notificationId(sbn.key),
                key = sbn.key,
                appName = appName,
                packageName = sbn.packageName,
                title = title,
                text = text,
                postedAtMs = sbn.postTime,
                ongoing = sbn.isOngoing,
            ),
        )
    }

    private fun notificationId(key: String): String =
        "notif_" + key.hashCode().toUInt().toString(16)
}
''',
)

# ---------------------------------------------------------------------------
# Pure JVM logic tests.

write(
    "plugins/assistant/src/test/java/com/anezium/rokidbus/plugin/assistant/AssistantMvpLogicTest.kt",
    r'''package com.anezium.rokidbus.plugin.assistant

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class AssistantMvpLogicTest {
    @Test
    fun `pipe mass uses deterministic steel geometry`() {
        val result = calculateEngineering(
            JSONObject()
                .put("operation", "pipe_mass")
                .put("outer_diameter_mm", 530.0)
                .put("wall_mm", 8.0)
                .put("length_m", 1.0)
                .put("quantity", 1.0),
        ) as AssistantToolResult.Json
        val json = JSONObject(result.text)
        assertEquals(102.986, json.getDouble("kg_per_m"), 0.001)
    }

    @Test
    fun `pile cylinder volume is metric and quantity aware`() {
        val result = calculateEngineering(
            JSONObject()
                .put("operation", "cylinder_volume")
                .put("diameter_mm", 1200.0)
                .put("length_m", 10.0)
                .put("quantity", 2.0),
        ) as AssistantToolResult.Json
        val json = JSONObject(result.text)
        assertEquals(22.619, json.getDouble("volume_m3"), 0.001)
    }

    @Test
    fun `meeting store has explicit lifecycle`() {
        val store = AssistantMeetingStore(maxChars = 100)
        assertFalse(store.active())
        assertTrue(store.start("Site meeting", 1000L) != null)
        assertTrue(store.active())
        assertTrue(store.add("Decision one"))
        assertTrue(store.add("Task two"))
        val snapshot = store.finish()
        assertEquals("Site meeting", snapshot?.title)
        assertEquals(listOf("Decision one", "Task two"), snapshot?.chunks)
        assertFalse(store.active())
    }

    @Test
    fun `sms contact resolver asks instead of silently choosing ambiguous people`() {
        val contacts = listOf(
            AssistantSmsContact(1, "Сергей Иванов", "+79990000001", "mobile", true, true),
            AssistantSmsContact(2, "Сергей Петров", "+79990000002", "mobile", true, true),
        )
        val ambiguous = resolveSmsContacts("Сергея", null, contacts)
        assertEquals(2, ambiguous.size)
        val clarified = resolveSmsContacts("Сергея", "Петров", contacts)
        assertEquals(1, clarified.size)
        assertEquals("Сергей Петров", clarified.single().displayName)
    }
}
''',
)
